
ej.Grid.Locale["es-CO"] = {
    EmptyRecord: "No hay registros para mostrar",
    DeleteOperationAlert: "No hay registros seleccionados para la operación de eliminar",
    EditOperationAlert: "No hay registros seleccionados para la operación de edición",
    SaveButton: "Guardar",
    CancelButton: "Cancelar",
    EditFormTitle: "Editar detalles de ",
    AddFormTitle: "Agregar nueva fila",
    Add: "Agregar",
    Edit: "Editar",
    Delete: "Eliminar",
    Update: "Actualizar",
    Cancel: "Cancelar",
    BatchSaveConifrm: "Are you sure you want to save changes?",
    ConfirmDelete: "¿Está seguro de eliminar el usuario seleccionado?",
    GroupDropArea: "Arrastrar y soltar Columna para Agrupar",
    ExcelExport: "Exportar a Excel",
    WordExport: "Exportar a Word",
    PdfExport: "Exportar a PDF",

};
ej.Pager.Locale["es-CO"] = {
    pagerInfo: "{0} de {1} páginas ({2} Registros)",
    firstPageTooltip: "Primera página",
    lastPageTooltip: "Ultima página",
    nextPageTooltip: "Siguiente página",
    previousPageTooltip: "Anterior página"
};
ej.ExcelFilter.Locale["es-CO"] = {
    SortTextAscending: "Ordenar de A a Z",
    SortTextDescending: "Ordenar de Z a A",
    SortNoSmaller: "Ordenar de Menor a Mayor",
    SortNoLarger: "Ordenar de Mayor a Menor",
    SortDateOldest: "Ordenar de antiguo a reciente",
    SortDateNewest: "Ordenar de reciente a antiguo",
    SortByColor: "Sort By Color",
    SortByCellColor: "Sort By Cell Color",
    SortByFontColor: "Sort By Font Color:",
    ClearFilter: "Borrar Filtro",
    TextFilter: "Filtros de Texto",
    NumberFilter: "Filtros de Número",
    DateFilter: "Filtros de Fecha",
    DateTimeFilter: "Filtros de Fecha",
    StringMenuOptions: [{ text: "Es igual a...", value: "equal" }, { text: "No es igual a...", value: "notequal" }, { text: "Comienza por", value: "startswith" }, { text: "Termina con", value: "endswith" }, { text: "Contiene", value: "contains" }, { text: "Filtro personalizado", value: "customfilter" }],
    NumberMenuOptions: [{ text: "Es igual a...", value: "Equal" }, { text: "No es igual a...", value: "NotEqual" }, { text: "Mayor que...", value: "GreaterThan" }, { text: "Mayor o igual que...", value: "GreaterThanOrEqual" }, { text: "Menor que...", value: "LessThan" }, { text: "Menor o igual que...", value: "LessThanOrEqual" }, { text: "Entre...", value: "Between" }, { text: "Filtro personalizado...", value: "customfilter" }],
    //GuidMenuOptions: [{ text: "Equal", value: "equal" }, { text: "Not Equal", value: "notequal" }, { text: "Custom Filter", value: "customfilter" }], 
    DateMenuOptions: [{ text: "Es igual a...", value: "equal" }, { text: "No es igual a...", value: "notequal" }, { text: "es anterior a", value: "lessthan" }, { text: "es anterior o igual a", value: "lessthanorequal" }, { text: "es posterior a", value: "greaterthan" }, { text: "es posterior o igual a", value: "greaterthanorequal" }, { text: "Entre", value: "between" }, { text: "Filtro perzonalizado", value: "customfilter" }],
    DatetimeMenuOptions: [{ text: "Es igual a", value: "equal" }, { text: "No es igual a", value: "notequal" }, { text: "Es anterior a", value: "lessthan" }, { text: "Es anterior o igual a", value: "lessthanorequal" }, { text: "Es posterior a", value: "greaterthan" }, { text: "Es posterior o igual a", value: "greaterthanorequal" }, { text: "Entre", value: "between" }, { text: "Filtro perzonalizado", value: "customfilter" }],
    Top10MenuOptions: [{ text: "Top", value: "top" }, { text: "Bottom", value: "bottom" }],
    Ok: "Aceptar",
    Cancel: "Cancelar",
    Search: "Buscar",
    NumericTextboxWaterMark: "Ingrese Valor",
    DatePickerWaterMark: "Seleccione Facha",
    DateTimePickerWaterMark: "Seleccione Facha",
    SelectAll: "Seleccionar todo",
    PredicateAnd: "Y",
    PredicateOr: "O",
    title: "Filtro Personalizado",
    MathCase: "",
    Showrowswhere: "Mostrar las filas en las cuales:",
    Blanks: "Vacías",
    True: "Verdadero",
    False: "Falso",
    CheckBoxStatusMsg: "No todos los elementos se muestran"
};
ej.Schedule.Locale["es-CO"] = {
    ReminderWindowTitle: "Fenêtre de rappel",
    CreateAppointmentTitle: "Crear",
    RecurrenceEditTitle: "Modifier répétition nomination",
    RecurrenceEditMessage: "Comment voulez-vous changer le cas dans la série?",
    RecurrenceEditOnly: "Seulement cette nomination",
    RecurrenceEditSeries: "La série entière",
    PreviousAppointment: "Atras",
    NextAppointment: "Adelante",
    AppointmentSubject: "Asunto",
    StartTime: "Hora de Inicio",
    EndTime: "Hora de finalización",
    AllDay: "Todo el día",
    Today: "Hoy",
    Recurrence: "Periocidad",
    Done: "Aceptar",
    Cancel: "Cancelar",
    Ok: "Ok",
    RepeatBy: "Repetir por",
    RepeatEvery: "répéter chaque",
    RepeatOn: "Repetir cada",
    Repeat: "Repetir",
    StartsOn: "Comienzo",
    Ends: "Finaliza",
    Summary: "résumé",
    Daily: "Diariamente",
    Weekly: "Semanalmente",
    Monthly: "Mensualmente",
    Yearly: "Anualmente",
    Every: "Cada",
    EveryWeekDay: "Todos los días de la semana",
    Never: "Nunca",
    After: "Despues de",
    On: "Finalizar el",
    Edit: "Modificar",
    RecurrenceDay: "días",
    RecurrenceWeek: "Semanas",
    RecurrenceMonth: "Meses",
    RecurrenceYear: "Años",
    The: "El",
    OfEvery: "de cada",
    First: "Primer",
    Second: "Segundo",
    Third: "Tercer",
    Fourth: "Cuarto",
    Last: "Ultimo",
    WeekDay: "jour de la semaine",
    WeekEndDay: "Jour de week-end",
    Subject: "sujet",
    Categorize: "Catégories",
    DueIn: "En raison",
    DismissAll: "rejeter tout",
    Dismiss: "rejeter",
    OpenItem: "Ouvrir l'élément",
    Snooze: "répétition",
    Day: "Día",
    Week: "Semana",
    WorkWeek: "Semana de trabajo",
    Month: "Mes",
    AddEvent: "Agregar Evento",
    CustomView: "Vue personnalisée",
    Agenda: "Agenda",
    Detailed: "Detallado",
    EventBeginsin: "Nomination commence dans",
    Editevent: "Modificar evento",
    Editseries: "Modificar serie",
    Times: "fois",
    Until: "jusqu'à",
    Eventwas: "rendez-vous était",
    Hours: "hrs",
    Minutes: "minutes",
    Overdue: "Atrasado",
    Days: "jour (s)",
    Event: "Sujet",
    Select: "sélectionner",
    Previous: "prev",
    Next: "suivant",
    Close: "Cerrar",
    Delete: "effacer",
    Date: "date",
    Showin: "montrer en",
    Gotodate: "Aller à la date",
    Resources: "RESSOURCES",
    RecurrenceDeleteTitle: "Supprimer répétition rendez-",
    Location: "emplacement",
    Priority: "priorité",
    RecurrenceAlert: "alerte",
    WrongPattern: "Le modèle de récurrence est pas valable",
    CreateError: "La durée de la nomination doit être plus courte que la façon dont elle se produit fréquemment. Raccourcir la durée ou changer le modèle de récurrence dans la boîte de dialogue Récurrence de rendez.",
    DragResizeError: "Impossible de replanifier une occurrence du rendez-vous récurrent. si elle saute sur une occurrence ultérieure du même rendez-vous.",
    StartEndError: "L'heure de fin doit être supérieur à l'heure de début",
    MouseOverDeleteTitle: "supprimer un rendez-",
    DeleteConfirmation: "Êtes-vous sûr de vouloir supprimer ce rendez-vous?",
    Time: "Temps",
    Occurrence: "repeticiones",
    StartTimeZone: "Commencez TimeZone",
    EndTimeZone: "TimeZone Fin",
    NoTitle: "Pas de titre",
    OverFlowAppCount: "plus rendez-vous (s)",
    AppointmentIndicator: "Cliquez pour plus de rendez-vous",
    EmptyResultText: "Pas de suggestions",
    BlockIntervalAlertTitle: "Alerte",
    BlockIntervalError: "L'intervalle de temps choisi a été bloqué et est indisponible pour la sélection.",
    RecurrenceDateValidation: "Certains mois ont moins de dates sélectionnées. Pour ces mois, l'occurrence tombera à la dernière date du mois",
    SeriesChangeAlert: "Les modifications apportées aux instances spécifiques de cette série seront annulées et ces rendez-vous seront identiques à la série"
};
