//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CuentasporPagar.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class CxPImpuestos
    {
        public int CxPIdImpuestos { get; set; }
        public Nullable<int> CxPRegimenId { get; set; }
        public Nullable<int> CxPConceptosId { get; set; }
        public Nullable<int> CxPTasasId { get; set; }
    
        public virtual CxPConceptos CxPConceptos { get; set; }
        public virtual CxPRegimen CxPRegimen { get; set; }
        public virtual CxPTasas CxPTasas { get; set; }
    }
}
