//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CuentasporPagar.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class CxPProceso
    {
        public int IdCxPProceso { get; set; }
        public string NitProveedor { get; set; }
        public string NombreProveedor { get; set; }
        public string EmailProveedor { get; set; }
        public string NPedidoSAP { get; set; }
        public string NFactura { get; set; }
        public Nullable<System.DateTime> FechaMaxRadicacion { get; set; }
        public Nullable<System.DateTime> FechaFactura { get; set; }
        public Nullable<double> Valor { get; set; }
        public Nullable<double> ValorTotal { get; set; }
        public string Moneda { get; set; }
        public string CategorizacionFactura { get; set; }
        public string Observaciones { get; set; }
        public string CentroCostos { get; set; }
        public string CuentaContable { get; set; }
        public Nullable<int> IdArea { get; set; }
        public Nullable<System.DateTime> FechaEntrega { get; set; }
        public string NombreRecibe { get; set; }
        public Nullable<System.DateTime> FechaRecepcion { get; set; }
        public string NHojaServicio { get; set; }
    }
}
