//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CuentasporPagar.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class CxPProveedor
    {
        public int IdCxPProveedor { get; set; }
        public string NIT { get; set; }
        public string DV { get; set; }
        public string CodigoSAP { get; set; }
        public string Nombre { get; set; }
        public string TipoPersona { get; set; }
        public string DescripcionRegimen { get; set; }
    }
}
