//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CuentasporPagar.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class RFPARAM
    {
        public decimal CCNUM { get; set; }
        public string CCID { get; set; }
        public string CCTABL { get; set; }
        public string CCCODE { get; set; }
        public string CCCODE2 { get; set; }
        public string CCCODE3 { get; set; }
        public string CCCODE4 { get; set; }
        public string CCCODE5 { get; set; }
        public decimal CCCODEN { get; set; }
        public decimal CCCODEN2 { get; set; }
        public string CCLANG { get; set; }
        public string CCALTC { get; set; }
        public string CCDESC { get; set; }
        public string CCSDSC { get; set; }
        public string CCNOT1 { get; set; }
        public string CCNOT2 { get; set; }
        public decimal CCUDC0 { get; set; }
        public decimal CCUDC1 { get; set; }
        public decimal CCUDC2 { get; set; }
        public decimal CCUDC3 { get; set; }
        public decimal CCUDC4 { get; set; }
        public decimal CCUDC5 { get; set; }
        public decimal CCUDC6 { get; set; }
        public decimal CCUDC7 { get; set; }
        public decimal CCUDC8 { get; set; }
        public decimal CCUDC9 { get; set; }
        public Nullable<decimal> CCUDV1 { get; set; }
        public Nullable<decimal> CCUDV2 { get; set; }
        public Nullable<decimal> CCUDV3 { get; set; }
        public Nullable<decimal> CCUDV4 { get; set; }
        public System.DateTime CCUDTS { get; set; }
        public Nullable<System.DateTime> CCUDDT { get; set; }
        public decimal CCRESV { get; set; }
        public System.DateTime CCENDT { get; set; }
        public string CCENUS { get; set; }
        public Nullable<System.DateTime> CCMNDT { get; set; }
        public string CCMNUS { get; set; }
        public string CCNOTE { get; set; }
        public string CFLAG1 { get; set; }
        public string CFLAG2 { get; set; }
        public string CFLAG3 { get; set; }
    }
}
