//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PanelAsistentes.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class PanelAsistCarga
    {
        public int IdPanelAsistCarga { get; set; }
        public Nullable<int> Orden { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public string Asistente { get; set; }
        public string Carga01 { get; set; }
        public string Carga02 { get; set; }
        public string Carga03 { get; set; }
        public string Carga04 { get; set; }
        public string Carga05 { get; set; }
        public string Carga06 { get; set; }
        public string Carga07 { get; set; }
        public string Carga08 { get; set; }
        public string Carga09 { get; set; }
        public string Carga10 { get; set; }
    }
}
